apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  type: ExternalName
    externalName: db.postgres.svc.cluster.local
